export const FETCH_EMPLOYEE='FETCH_EMPLOYEE'
export const FETCH_EMPLOYEE_BY_ID='FETCH_EMPLOYEE_BY_ID'

export const INSERT_EMPLOYEE='INSERT_EMPLOYEE'

export const UPDATE_EMPLOYEE='UPDATE_EMPLOYEE'

export const DELETE_EMPLOYEE_BY_ID='DELETE_EMPLOYEE_BY_ID'